### ISSUE TITLE
D003 - Versão Inicial do GDD

### ISSUE THREAD

**Issue by edsomjr** [ShutUpPaulo/IJE_Equipe_01#13]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/D003_Versao_Inicial_do_GDD.txt

**Comment by edsomjr** [comment]
Paulo,

para fechar esta issue ficaram faltando ainda:

1) Tabela de revisões;
2) Objetivo do jogo.
3) Controles.

Os últimos dois itens podem ser retirados do documento de visão.

**Comment by ShutUpPaulo** [comment]
Professor, veja se está ok agora. No entanto, apresenta alguns problemas ainda. A tabela de revisão tá pegando todos os gits ao inves de apenas os relacionados ao GDD. Eu, honestamente, n faço a menor ideia de como fazer isso. E a tabela tá ultrapassando as margens impostas também.

**Comment by edsomjr** [comment]
Paulo,

faça esta tabela de revisão "manualmente", pois os problemas relatados são provenientes do pacote que você está utilizando para importar os commits do git.

Em relação a esta issue, ficou faltando ainda os objetivos do jogo. Como falei antes, você tem estas informações no documento de visão.

**Comment by ShutUpPaulo** [comment]
Pronto, professor. Tá tudo ok agora.
