### ISSUE TITLE
P006 - Tela de Apresentação

### ISSUE THREAD

**Issue by edsomjr** [ShutUpPaulo/IJE_Equipe_01#18]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/P006_Tela_de_Apresentacao.txt

**Comment by edsomjr** [comment]
Lucas e Bruno,

é preciso implementar as telas de front end que estão descritas no GDD.

**Comment by ShutUpPaulo** [comment]
Professor, confira se já está em um nível aceitável.

**Comment by edsomjr** [comment]
Caros,

atualizei a engine para a versão v0.0.4. Esta será a última vez que quebrarei a interface. Por conta desta útlima mudança, não consigo compilar mais o código de vocês. Se puderem arrumar melhor, senão me procurem amanhã (observação: aula no Darcy) que eu faço a adaptação.
