### ISSUE TITLE
D001 - Versão Inicial do Documento de Visão

### ISSUE THREAD

**Issue by edsomjr** [ShutUpPaulo/IJE_Equipe_01#4]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/D001_Versao_Inicial_do_Documento_de_Visao.txt

**Comment by edsomjr** [comment]
Paulo,

o documento está bem escrito, e é nesta direção mesmo. Seguem algumas considerações:

1) Talvez 14 anos não seja suficiente para a classificação indicativa. Seria bom consultar os critérios da classificação brasileira;

2) Os dados pessoais da equipe ficam no documento de apresentação da equipe. Neste documento, fica apenas o contato da equipe como um todo (e-mail. GitHub, etc);

3) Adicione uma imagem de um teclado ilustrando os controles, mesmo que ainda não estejam definidos;

4) Após a inserção dos logos e destas considerações poderemos fechar esta issue.

Obs.: melhor utilizar o formato .tex para versionar os documentos, e não .doc, .odt ou .docx.

**Comment by ShutUpPaulo** [comment]
Professor, subi a versão .zip pois tinha algumas imagens que eu estava tentando adicionar ao arquivo, porém não obtive sucesso e sinceramente acabei desistindo de tentar, já que eu ainda tenho q passar esse documento pro InDesign. No entanto, seria muito grato se você pudesse me ajudar com a manipulação de imagens sem que eu perca o formato de artigo.

**Comment by edsomjr** [comment]
Paulo,

veja as alterações que promovi. Este template pode ser utilizado para a escrita do GDD. Embora a versão final do documento de visão tenha que ser mais atrativa visualmente, o GDD não tem esta necessidade, e pode ser feito todo em Latex. 

Em relação ao posicionamento das figuras no GDD, elas não precisam ficar exatamente após o parágrafo que as cita: o Latex tenta otimizar a utilização do espaço, de modo que a figura pode ficar antes ou depois. Para isso, utilizando as referências: ao invés de escrever "conforme visto na figura abaixo/a seguir", escrevemos "conforme mostrado na Figura \ref{label}", onde o label é o identificador definido por você mesmo dentro do ambiente figure com o comando \label{}, após o \caption{}.
