### ISSUE TITLE
G009 - Efeitos Sonoros

### ISSUE THREAD

**Issue by edsomjr** [ShutUpPaulo/IJE_Equipe_01#43]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/G009_Efeitos_Sonoros.txt

**Comment by ShutUpPaulo** [comment]
Os que estão na pasta sounds já atendem essa issue? Não estão do jogo todo lá, mas a atualização tanto nos efeitos sonoros quanto nas musicas estao sendo frequentes.
