### ISSUE TITLE
G003 - Documento de Apresentação da Equipe

### ISSUE THREAD

**Issue by edsomjr** [ShutUpPaulo/IJE_Equipe_01#5]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/G003_Documento_de_Apresentacao_da_Equipe.txt

**Comment by edsomjr** [comment]
Hugo,

não é preciso colocar o texto motivador da issue no documento. Faltam os dados dos demais membros, e agora seria uma boa hora para substituir o formato do documento para .tex.

**Comment by ShutUpPaulo** [comment]
Agora tem as informações de todos os membros da equipe e está em .txt
