### ISSUE TITLE
G004 - Cronograma

### ISSUE THREAD

**Issue by edsomjr** [ShutUpPaulo/IJE_Equipe_01#6]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/G004_Cronograma.txt

**Comment by edsomjr** [comment]
Duas observações em relação ao cronograma:

1) detalhar melhor quais seriam as atividades desenvolvidas nos encontros/reuniões previstas (codificar áudio, produzir sprites, definir música, etc).

2) Uma imagem com um diagrama de Gantt é melhor do que um documento para representar um cronograma. Há várias ferramentas, online e livres, que permitem montar e exportar tais diagramas.

**Comment by ShutUpPaulo** [comment]
Por motivos de complicações ao longo do processo, fizemos apenas o cronograma até a primeira entrega. A medida que a gente conseguir finalizar as atividades da 1a entrega a gente vai definindo as tarefas das demais entregas.

**Comment by edsomjr** [comment]
Paulo,

o cronograma de fato é um documento dinâmico, mas você pode traçar as linhas gerais utilizando as tasks/issues como guia. Preencha o cronograma com as issues para fecharmos esta tarefa, e a medida que o desenvolvimento for avançando, você vai atualizando o documento de acordo com a necessidade.

**Comment by ShutUpPaulo** [comment]
Professor, veja se está de acordo com o cronograma agora.

**Comment by edsomjr** [comment]
Paulo,

é isso mesmo. Lembre-se de atualizar as datas e os prazos, para que o cronograma cumpra o seu papel, que é o de apoiar as decisões no processo de desenvolvimentos, elencando as prioridades.
