### ISSUE TITLE
P001 - Ambiente de Desenvolvimento

### ISSUE THREAD

**Issue by edsomjr** [ShutUpPaulo/IJE_Equipe_01#7]
https://github.com/edsomjr/IJE/blob/master/tasks/P001_Ambiente_de_Desenvolvimento.txt

**Comment by lucaslrt** [comment]
https://github.com/ShutUpPaulo/ManaTeam/commit/5ae5af4c8282fbbde22dda4e21fd197d498debce

**Comment by edsomjr** [comment]
Lucas,

algumas pequenas observações/comentários:

1) A API que utilizamos para os gráficos é a SDL, e não SQL;
2) Bash é o terminal do Linux (Bourne Again Shell): o depurador padrão da suite GNU é o gdb (GNU Debugger);
3) Faltou o editor de texto de vocês (Sublime? Vim?);
4) Embora seja possível utilizar o shell script no jogo, é improvável. Mude a linguagem de script para Lua, que usaremos na disciplina;
5) A numeração do item do compilador deve ser 9, e não 8.

Corrija estes pequenos pontos (coisa rápida, não deve levar nem 10 minutos) e submeta novamente para fecharmos esta issue.

**Comment by lucaslrt** [comment]
767aa7861ea08cae5cda08d7864b89134c9e0cd6
