### ISSUE TITLE
P003 - Janela

### ISSUE THREAD

**Issue by edsomjr** [ShutUpPaulo/IJE_Equipe_01#9]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/P003_Janela.txt

**Comment by edsomjr** [comment]
Lucas,

a criação da janela deve ser feita dentro do contexto da nossa arquitetura, isto é, no construtor da classe do jogo.

**Comment by lucaslrt** [comment]
Criação de janela refeita.

**Comment by edsomjr** [comment]
Lucas,

algumas dicas para as próximas tarefas:

1) Reorganize os diretórios do seu código: o seu jogo não se chama "test" e a pasta principal não deve ser "engine";

2) Você está alterando o código da engine para inserir seu jogo: contudo, a engine e o conteúdo do jogo devem ser separados logicamente ao longo do processo. Se você continuar neste caminho, não conseguirá utilizar as novas versões da engine ou terá muito retrabalho de ficar copiando e colando código. Faça como eu tenho feito nos exemplos: os códigos da pasta test correspondem aos códigos de um jogo fictício que utilizam a engine, através da herança e polimorfismo. Utilize estes códigos como guias para fazer a implementação do jogo separada da engine;

3) Remova os warnings de compilação: um warning é "meio erro": são pontos onde o código pode vir a se comportar de forma distinta do que queremos.

Se quiser apareça na minha sala na quarta, antes da aula (13 hrs) que sento contigo para fazermos juntos esta reorganização.

**Comment by lucaslrt** [comment]
Olá professor,

Eu gostaria de saber se amanhã vou poder ir até a sua sala as 13 para você poder me ajudar a passar o cógigo para a engine atualizada.
